version: "3"

services:
  apps:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    tty: true
    volumes:
      - type: bind
        source: ./nextjs-react-project
        target: /nextjs-react-project

volumes:
  bin:
  out: